server:
  port: 8093

spring:
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


  #### database ??
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: kimhk11
    password: 1234

#### mybatis ??
mybatis:
  config-location: classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sql/**/*.xml
  #type-aliases-package: com.jjang051.board.dto  # comma

#### log ??  fatal > error > warn > info > debug
logging:
  level:
    root: info
    '[com.khk11.todo]': info

file:
  path: C:/upload/