server:
  port: 8095

spring:
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


  #### database ??
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: kimhk13
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  #update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: oracle
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect
  ### 구글 로그인 정보 ###
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 142804686920-odou16u9o7dvekpplh7opd9lerblrefb.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: ukzGlMtu3xj8ieJgRrii
            client-secret: KljQvw7jwg
            scope:
              - nickname
              - email

            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8094/login/oauth2/code/naver

          kakao:
            client-id: ffbdea517507bb8796fada73af11ebbe
            client-secret: 65KX8LYR2I7jzpwtUSnVfINWABWCrRot
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8094/login/oauth2/code/kakao
            client-authentication-method: client_secret_post

          github:
            client-id: b3e34960d32298cfd55b
            client-secret: 1c30996e2af44acfed507f18693c14d6724fe081
            scope:
              - user
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



  mail:
    host: smtp.naver.com
    port: 465
    username: kimhg1103@naver.com
    password: gurrl101004
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enabled: true
            trust: smtp.naver.com
    protocol: smtps



#### mybatis ??
#mybatis:
#  config-location: classpath:mapper/config/config.xml
#  mapper-locations: classpath:mapper/sql/**/*.xml
  #type-aliases-package: com.jjang051.board.dto  # comma

#### log ??  fatal > error > warn > info > debug
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 파라미터 보여준다.

file:
  path: C:/outstargram/

pagination:
  size: 5