server:
  port: 8090

spring:
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
  mail:
    host: smtp.naver.com
    port: 465
    username: kimhg1103@naver.com
    password: gurrl101004
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enabled: true
            trust: smtp.naver.com
    protocol: smtps


  #### database 설정
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: kimhk11
    password: 1234

#### mybatis 설정
mybatis:
  config-location: classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sql/**/*.xml
  #type-aliases-package: com.jjang051.board.dto  # comma

#### log 설정  fatal > error > warn > info > debug
logging:
  level:
    root: info
    '[com.jjang051.board]': info

file:
  path: C:/upload/